services:
  sipi-frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: sipi-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app                    # Monta tu código
      - /app/node_modules         # VOLUMEN ANÓNIMO: usa el de la imagen, IGNORA el del host
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100